name: Build & test

on:
  push:
    branches: [master, aarch64]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            name: Linux x86_64
          - os: macos-13
            name: macOS x86_64
          - os: macos-14
            name: macOS aarch64
          - os: windows-2022
            name: Windows x86_64
            cmake-generator: -G "Visual Studio 17 2022" -A x64

    name: ${{ matrix.name }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev xorg-dev libglu1-mesa-dev ninja-build

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install ninja

      - name: Configure (Unix)
        if: runner.os != 'Windows'
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON ${{ matrix.cmake-generator }}

      - name: Configure (Windows)
        if: runner.os == 'Windows'
        run: |
          cmake -B build -DBUILD_TESTS=ON ${{ matrix.cmake-generator }}

      - name: Build
        run: cmake --build build --config Release -j2

      - name: Test
        run: ctest --test-dir build --build-config Release --label-regex libs-core --output-on-failure
